import type { Env } from '../src/lib/env'
import process from 'node:process'

export const TEST_ENV: Record<keyof Env, string> = {
  NODE_ENV: 'development',
  PORT: '3000',
  BASE_URL: 'http://localhost:3000',
  WEB_ORIGIN: 'http://localhost:5173',
  COOKIE_DOMAIN: '',
  AUTH_SECRET: 'integration-tests-secret-not-used-for-anything-real',
  POSTGRES_USER: process.env.POSTGRES_USER ?? 'kinora',
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD ?? 'kinora',
  POSTGRES_HOST: process.env.POSTGRES_HOST ?? 'localhost',
  POSTGRES_PORT: process.env.POSTGRES_PORT ?? '5436',
  POSTGRES_DB: 'kinora_test',
  STORAGE_DIR: '.data/test-artifacts',
  GOOGLE_CLIENT_ID: 'test',
  GOOGLE_CLIENT_SECRET: 'test',
  GITHUB_CLIENT_ID: 'test',
  GITHUB_CLIENT_SECRET: 'test',
  KINORA_CLOUD: 'false',
  KINORA_DEMO: 'false',
  INGEST_RATE_LIMIT: '600',
  TRPC_RATE_LIMIT: '300',
  KINORA_RETENTION_DAYS: '0',
  KINORA_KEEP_LAST_RUNS: '0',
  KINORA_ARTIFACT_RETENTION_DAYS: '0',
  POLAR_ACCESS_TOKEN: '',
  POLAR_WEBHOOK_SECRET: '',
  POLAR_PRODUCT_TEAM_ID: 'prod_team_test',
  POLAR_PRODUCT_PRO_ID: 'prod_pro_test',
  S3_ENDPOINT: '',
  S3_REGION: '',
  S3_BUCKET: '',
  S3_ACCESS_KEY_ID: '',
  S3_SECRET_ACCESS_KEY: '',
  SLACK_CLIENT_ID: 'test-slack-client',
  SLACK_CLIENT_SECRET: 'test-slack-secret',
  SMTP_HOST: '',
  SMTP_PORT: '',
  SMTP_USER: '',
  SMTP_PASS: '',
  SMTP_FROM: '',
  SENTRY_DSN: '',
  FEEDBACK_TRACKER_API_KEY: '',
  FEEDBACK_TRACKER_PROJECT_ID: '',
  FEEDBACK_TRACKER_WORKSPACE_ID: '',
  FEEDBACK_TRACKER_API_URL: '',
}
