import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema
    .createTable('user', (t) => {
      t.text('id').primary()
      t.text('name').notNullable()
      t.text('email').notNullable()
      t.boolean('email_verified').notNullable().defaultTo(false)
      t.text('image')
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.unique(['email'], { indexName: 'user_email_unique' })
    })
    .createTable('verification', (t) => {
      t.text('id').primary()
      t.text('identifier').notNullable()
      t.text('value').notNullable()
      t.timestamp('expires_at', { useTz: false }).notNullable()
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.index(['identifier'], 'verification_identifier_idx')
    })
    .createTable('apikey', (t) => {
      t.text('id').primary()
      t.text('config_id').notNullable().defaultTo('default')
      t.text('name')
      t.text('start')
      t.text('prefix')
      t.text('key').notNullable()
      t.text('reference_id').notNullable()
      t.integer('refill_interval')
      t.integer('refill_amount')
      t.timestamp('last_refill_at', { useTz: false })
      t.boolean('enabled').defaultTo(true)
      t.boolean('rate_limit_enabled').defaultTo(true)
      t.integer('rate_limit_time_window').defaultTo(86400000)
      t.integer('rate_limit_max').defaultTo(10)
      t.integer('request_count').defaultTo(0)
      t.integer('remaining')
      t.timestamp('last_request', { useTz: false })
      t.timestamp('expires_at', { useTz: false })
      t.timestamp('created_at', { useTz: false }).notNullable()
      t.timestamp('updated_at', { useTz: false }).notNullable()
      t.text('permissions')
      t.text('metadata')
      t.index(['config_id'], 'apikey_configId_idx')
      t.index(['reference_id'], 'apikey_referenceId_idx')
      t.index(['key'], 'apikey_key_idx')
    })
    .createTable('account', (t) => {
      t.text('id').primary()
      t.text('account_id').notNullable()
      t.text('provider_id').notNullable()
      t.text('user_id').notNullable().references('id').inTable('user').onDelete('CASCADE')
      t.text('access_token')
      t.text('refresh_token')
      t.text('id_token')
      t.timestamp('access_token_expires_at', { useTz: false })
      t.timestamp('refresh_token_expires_at', { useTz: false })
      t.text('scope')
      t.text('password')
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.timestamp('updated_at', { useTz: false }).notNullable()
      t.index(['user_id'], 'account_userId_idx')
    })
    .createTable('session', (t) => {
      t.text('id').primary()
      t.timestamp('expires_at', { useTz: false }).notNullable()
      t.text('token').notNullable()
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.timestamp('updated_at', { useTz: false }).notNullable()
      t.text('ip_address')
      t.text('user_agent')
      t.text('user_id').notNullable().references('id').inTable('user').onDelete('CASCADE')
      t.unique(['token'], { indexName: 'session_token_unique' })
      t.index(['user_id'], 'session_userId_idx')
    })
    .createTable('project', (t) => {
      t.text('id').primary()
      t.text('user_id').notNullable().references('id').inTable('user').onDelete('CASCADE')
      t.text('slug').notNullable()
      t.text('name').notNullable()
      t.text('description')
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.unique(['user_id', 'slug'], { indexName: 'project_user_slug_uniq' })
      t.index(['user_id'], 'project_userId_idx')
    })
    .createTable('run', (t) => {
      t.text('id').primary()
      t.text('project_id').notNullable().references('id').inTable('project').onDelete('CASCADE')
      t.timestamp('started_at', { useTz: false }).notNullable()
      t.integer('duration').notNullable()
      t.jsonb('counts').notNullable()
      t.jsonb('counts_by_tag').notNullable().defaultTo(knex.raw(`'{}'::jsonb`))
      t.text('playwright_version')
      t.jsonb('git')
      t.jsonb('ci')
      t.integer('shards')
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.index(['project_id'], 'run_projectId_idx')
    })
    .createTable('test', (t) => {
      t.text('id').primary()
      t.text('run_id').notNullable().references('id').inTable('run').onDelete('CASCADE')
      t.text('project_id').notNullable().references('id').inTable('project').onDelete('CASCADE')
      t.text('test_key').notNullable()
      t.text('title').notNullable()
      t.jsonb('title_path').notNullable()
      t.text('file').notNullable()
      t.integer('line').notNullable()
      t.integer('column').notNullable()
      t.text('project_name').notNullable()
      t.text('status').notNullable()
      t.boolean('ok').notNullable()
      t.integer('duration').notNullable()
      t.integer('retries').notNullable()
      t.jsonb('tags').notNullable()
      t.jsonb('annotations').notNullable()
      t.jsonb('errors').notNullable()
      t.jsonb('attachments').notNullable()
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.index(['run_id'], 'test_runId_idx')
      t.index(['project_id', 'test_key'], 'test_project_key_idx')
    })
    .createTable('artifact', (t) => {
      t.text('id').primary()
      t.text('project_id').notNullable().references('id').inTable('project').onDelete('CASCADE')
      t.text('run_id').notNullable().references('id').inTable('run').onDelete('CASCADE')
      t.text('test_id').references('id').inTable('test').onDelete('CASCADE')
      t.text('name').notNullable()
      t.text('content_type').notNullable()
      t.text('storage_key').notNullable()
      t.text('sha1')
      t.integer('size')
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.index(['run_id'], 'artifact_runId_idx')
    })
    .createTable('subscription', (t) => {
      t.text('user_id').primary().references('id').inTable('user').onDelete('CASCADE')
      t.text('polar_customer_id').notNullable()
      t.text('tier').notNullable().defaultTo('free')
      t.text('status')
      t.text('product_id')
      t.timestamp('current_period_end', { useTz: false })
      t.boolean('cancel_at_period_end').notNullable().defaultTo(false)
      t.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
    })
    .createTable('slack_integration', (t) => {
      t.text('project_id').primary().references('id').inTable('project').onDelete('CASCADE')
      t.text('webhook_url').notNullable()
      t.text('channel')
      t.text('team_name')
      t.text('policy').notNullable().defaultTo('on-failure')
      t.boolean('enabled').notNullable().defaultTo(true)
      t.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
      t.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now())
    })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema
    .dropTableIfExists('slack_integration')
    .dropTableIfExists('subscription')
    .dropTableIfExists('artifact')
    .dropTableIfExists('test')
    .dropTableIfExists('run')
    .dropTableIfExists('project')
    .dropTableIfExists('session')
    .dropTableIfExists('account')
    .dropTableIfExists('apikey')
    .dropTableIfExists('verification')
    .dropTableIfExists('user')
}
