name: kinora
services:
  pg:
    container_name: kinora_postgres
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: kinora
      POSTGRES_PASSWORD: kinora
      POSTGRES_DB: kinora
    ports:
      - '5436:5432'
